CURSO_NO_ENCONTRADO = "No he podido encontrar el curso - , recuerda escribir bien el nombre del curso, consulta nuestra oferta de cursos en: http://opencampus.utpl.edu.ec/courses"
CURSO_NO_ECONTRADO2 = ", recuerda escribir bien el nombre del curso, consulta nuestra oferta de cursos en: http://opencampus.utpl.edu.ec/courses"
PREGUNTA_NO_ENCONTRADA = "No he podido encontrar respuesta a tu pregunta, puedes revisar las preguntas frecuentes para más informacion http://opencampus.utpl.edu.ec/faq"
RESPUESTA_AYUDA = "Puedes revisar la informacion de como usar el bot adelante: "
TELEGRAM_CHANNEL = "t.me/OCCChatBot ...."
ERROR = "Lo siento :( ha ocurrido un error"